# Generated by Django 3.0.3 on 2020-08-06 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200806_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 6, 3, 18, 9, 904018, tzinfo=utc)),
        ),
    ]
